In [2]:
import pandas as pd

df=pd.DataFrame([[1,2,3],[2,3],[1,2,3,4]],columns=['a','b','c','d'],index=['a','b','c'])
print(df)

   a  b    c    d
a  1  2  3.0  NaN
b  2  3  NaN  NaN
c  1  2  3.0  4.0

In [3]:
print(df.columns)

Index(['a', 'b', 'c', 'd'], dtype='str')

In [4]:
print(df.index)

Index(['a', 'b', 'c'], dtype='str')

In [7]:
# print(df.head(2))
print(df.tail(2))

   a  b    c    d
b  2  3  NaN  NaN
c  1  2  3.0  4.0

In [6]:
print(df.dtypes)

a      int64
b      int64
c    float64
d    float64
dtype: object

In [ ]:
df.info()      #to check data types and other info

<class 'pandas.DataFrame'>
Index: 3 entries, a to c
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       2 non-null      float64
 3   d       1 non-null      float64
dtypes: float64(2), int64(2)
memory usage: 120.0+ bytes

In [11]:
df.describe()         # further info about the data

              a         b    c    d
count  3.000000  3.000000  2.0  1.0
mean   1.333333  2.333333  3.0  4.0
std    0.577350  0.577350  0.0  NaN
min    1.000000  2.000000  3.0  4.0
25%    1.000000  2.000000  3.0  4.0
50%    1.000000  2.000000  3.0  4.0
75%    1.500000  2.500000  3.0  4.0
max    2.000000  3.000000  3.0  4.0

In [12]:
df.nunique()         # to check unique values in each column

a    2
b    2
c    1
d    1
dtype: int64

In [13]:
df

   a  b    c    d
a  1  2  3.0  NaN
b  2  3  NaN  NaN
c  1  2  3.0  4.0

In [16]:
df2=pd.DataFrame([["A","B","C"],["D","E","F"]],columns=[1,2,3])
print(df2)

   1  2  3
0  A  B  C
1  D  E  F

In [18]:
df2.nunique()

1    2
2    2
3    2
dtype: int64

In [19]:
df2[1].unique()

<StringArray>
['A', 'D']
Length: 2, dtype: str

In [27]:
df.shape
# df2.shape

(3, 4)