In [31]:
import pandas as pd

coffee=pd.read_csv("./warm-up data/coffee.csv")
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [14]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday       Latte          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [17]:
coffee.sort_values(["Units Sold"],ascending=[False])
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [7]:
coffee.loc[10,"Coffee Type"]="Latte"
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [8]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday       Latte          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [9]:
coffee.to_csv("./warm-up data/coffee.csv",index=False)

In [18]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday       Latte          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [33]:
coffee.sort_values(["Units Sold"],ascending=False,inplace=True)

In [34]:
coffee.to_csv("./warm-up data/coffee.csv",index=False)

In [43]:
coffee.loc[14,"Coffee Type"]="Black Coffee"
coffee["Revenue"] = coffee["Units Sold"] * 10
coffee.head()

          Day Coffee Type  Units Sold  Revenue
10   Saturday       Latte        45.0    450.0
8      Friday    Espresso        45.0    450.0
12     Sunday    Espresso        45.0    450.0
6    Thursday    Espresso        40.0    400.0
4   Wednesday    Espresso        35.0    350.0

In [44]:
coffee.to_csv("./warm-up data/coffee.csv",index=False)