In [3]:
import pandas as pd

coffee =pd.read_csv("./warm-up data/coffee.csv")
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [29]:
coffee.index=coffee["Day"]
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [36]:
coffee.loc["Monday":"Wednesday","Units Sold"]

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Name: Units Sold, dtype: int64

In [ ]:
import pandas as pd

results = pd.read_csv('./data/results.csv')
results.head()

In [ ]:
results.sample(5)
# to take random indices from the data frame

In [ ]:
#results.loc[0]   ## just the first row
#results.loc[0,8]    ## from-to situation
# results.loc[[0,1,100]]    ## just some random indices
results.loc[[0,3],["year","type"]]

In [ ]:
results.iloc[[0,1],[1,3]]     # iloc is used to access the data frame by position, not by label