In [2]:
import pandas as pd

coffee =pd.read_csv("./warm-up data/coffee.csv")
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [29]:
coffee.index=coffee["Day"]
coffee.head()

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [36]:
coffee.loc["Monday":"Wednesday","Units Sold"]

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Name: Units Sold, dtype: int64

In [11]:
coffee.loc[2,"Units Sold"]=50
coffee.loc[2,"Coffee Type"]="Black Coffee"
coffee.head()

         Day   Coffee Type  Units Sold
0     Monday      Espresso          25
1     Monday         Latte          15
2    Tuesday  Black Coffee          50
3    Tuesday         Latte          20
4  Wednesday      Espresso          35

In [17]:
coffee["Coffee Type"]      # to access a specific column in the data frame

0         Espresso
1            Latte
2     Black Coffee
3     Black Coffee
4         Espresso
5            Latte
6         Espresso
7            Latte
8         Espresso
9            Latte
10        Espresso
11           Latte
12        Espresso
13           Latte
Name: Coffee Type, dtype: str

In [24]:
coffee.sort_values(["Units Sold","Day"],ascending=[1,0])     # to sort the data frame by a specific column

          Day   Coffee Type  Units Sold
1      Monday         Latte          15
3     Tuesday  Black Coffee          20
5   Wednesday         Latte          25
0      Monday      Espresso          25
7    Thursday         Latte          30
4   Wednesday      Espresso          35
13     Sunday         Latte          35
11   Saturday         Latte          35
9      Friday         Latte          35
6    Thursday      Espresso          40
12     Sunday      Espresso          45
10   Saturday      Espresso          45
8      Friday      Espresso          45
2     Tuesday  Black Coffee          50

In [28]:
for index,row in coffee.iterrows():
    print(index,end=": ")
    print(row["Units Sold"])

0: 25
1: 15
2: 50
3: 20
4: 35
5: 25
6: 40
7: 30
8: 45
9: 35
10: 45
11: 35
12: 45
13: 35

In [4]:
import pandas as pd

results = pd.read_csv('./data/results.csv')
results.head()

/tmp/ipykernel_37744/777234667.py:3: DtypeWarning: Columns (0: tied) have mixed types. Specify dtype option on import or set low_memory=False.
  results = pd.read_csv('./data/results.csv')

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [ ]:
results.sample(5)
# to take random indices from the data frame

In [ ]:
#results.loc[0]   ## just the first row
#results.loc[0,8]    ## from-to situation
# results.loc[[0,1,100]]    ## just some random indices
results.loc[[0,3],["year","type"]]

In [5]:
results.iloc[[0,1],[1,3]]     # iloc is used to access the data frame by position, not by label

     type                   event
0  Summer  Singles, Men (Olympic)
1  Summer  Doubles, Men (Olympic)

In [7]:
results.loc[1,"team"]="NaN"   # to change the value of a specific cell in the data frame
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [8]:
results.type

0        Summer
1        Summer
2        Summer
3        Summer
4        Summer
          ...
80666    Summer
80667    Summer
80668    Summer
80669    Summer
80670    Summer
Name: type, Length: 80671, dtype: str