First of all we need to import Pandas library.

In [4]:
import pandas as pd

DataFrame:
It is the table. It is array of individual entries.

In [20]:
pd.DataFrame({"a":[1,2,3],"b":[4,5,6]})

   a  b
0  1  4
1  2  5
2  3  6

In [21]:
pd.DataFrame({"a":["I am Ilyan","I am learning pandas."]})

                       a
0             I am Ilyan
1  I am learning pandas.

This is used with dictionaries.
keys = colomns
values = rows

We can change the index from starting from 0 to any other index.

In [7]:
pd.DataFrame({"A":[1,2,3],"B":[4,5,6]},index=["1","2","3"])

   A  B
1  1  4
2  2  5
3  3  6

Series:
It is just a list of values.
It has only 1 colomn.

In [23]:
pd.Series([1,2,3],index=["a","b","c"],name="My_Series")

a    1
b    2
c    3
Name: My_Series, dtype: int64

# Reading Data from CSV file

In [24]:
data_csv=pd.read_csv("dataset.csv")

**.shape**
we use .shape to check how much dataset actually is.

In [25]:
data_csv.shape

(6, 3)

In [26]:
data_csv.head()

   ID  Value_A  Value_B
0   1       10      100
1   2       25      250
2   3       42      420
3   4       55      550
4   5       88      880

we can use
index_col=0 to not make a new colomn at the start for index

In [27]:
data_csv=pd.read_csv("dataset.csv",index_col="ID")
data_csv.head()

    Value_A  Value_B
ID
1        10      100
2        25      250
3        42      420
4        55      550
5        88      880

In [28]:
pd.DataFrame({"fruits":["Apple","Banana"]})

   fruits
0   Apple
1  Banana